# Basic Settings
theme: jekyll-theme-cayman
title: Shang - Web3 Social Tipping
description: Less is More, Peg is Core
baseurl: "/shang.tips"
url: "https://cloud-cottage.github.io"

# Multilingual Settings
languages: ["en", "zh_cn"]
exclude_from_localizations: ["assets", "css", "js", "_posts"]

# Permalink Structure
permalink: /:path/:basename:output_ext
collections:
  cn:
    output: true
    permalink: /cn/:path/:basename:output_ext
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title:output_ext

# others
show_downloads: false
cache_buster: 4
plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag