title: OneShang
description: A decentralized application built for the future
baseurl: "/shang.tips"
url: "https://cloud-cottage.github.io"
theme: jekyll-theme-cayman
show_downloads: false
sass:
  style: compressed
  sass_dir: assets/css
cache_buster: 3
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: true