# Basic Settings
theme: jekyll-theme-cayman
title: Shang - Web3 Social Tipping
description: Less is More, Peg is Core

# Multilingual Settings
languages: ["en", "zh"]
exclude_from_localizations: ["assets", "css", "js", "_posts"]

# Permalink Structure
permalink: /:lang/:path/:basename:output_ext
collections:
  en:
    output: true
    permalink: /en/:path/:basename:output_ext
  zh:
    output: true
    permalink: /zh/:path/:basename:output_ext
  posts:
    output: true
    permalink: /:lang/blog/:year/:month/:day/:title:output_ext
    
# others
show_downloads: false
sass:
  style: compressed
  sass_dir: assets/css
cache_buster: 3
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one