# 基本设置
theme: jekyll-theme-cayman
title: Shang - Web3 Social Tipping
description: Less is More, Peg is Core

# 多语言设置
languages: ["en", "zh"]
exclude_from_localizations: ["assets", "css", "js"] # 排除不需要翻译的文件夹

# GitHub Pages 默认设置
permalink: /:path/:basename:output_ext

baseurl: "/shang.tips"
url: "https://cloud-cottage.github.io"
show_downloads: false
sass:
  style: compressed
  sass_dir: assets/css
cache_buster: 3
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one