title: My DApp Showcase
description: A decentralized application built for the future
baseurl: "/shang.tips"
url: "https://cloud-cottage.github.io"
theme: jekyll-theme-cayman
show_downloads: false
sass:
  style: compressed
  sass_dir: .
cache_buster: 3